#!/bin/bash

# Encodes video to h264 with denoise and grading LUT applied for Youtube
# Usage:
#       $ ./ff_264 <input_file> <lut_file> <output_file>

ffmpeg -y -i "$1" -c:v libx264 -crf 16 -preset fast -profile:v main -pix_fmt yuv420p -vf atadenoise,lut3d=file="$2" -c:a copy "$3"
