#!/bin/bash

# Generates side-by-side comparison of two videos
# Usage:
#       $ ./ff_sidebyside <video_1> <video_2>

ffmpeg -y -i "$1" -i "$2" -filter_complex "[0:v:0]pad=iw*2:ih[bg]; [bg][1:v:0]overlay=w" sidebyside.mkv